[global]
basepath = "~/.gossamer/westend-local-alice"
log = "info"
metrics-address = ":9876"

[log]
core = ""
network = ""
rpc = ""
state = ""
runtime = ""
babe = ""
grandpa = ""
sync = ""
digest = ""

[init]
genesis = "./chain/westend-local/westend-local-spec-raw.json"

[account]
key = "alice"
unlock = ""

[core]
roles = 4
babe-authority = true
grandpa-authority = true
babe-lead = true

[network]
port = 7001
nobootstrap = false
nomdns = false

[rpc]
enabled = true
ws = true
port = 8545
host = "localhost"
modules = [
    "system",
    "author",
    "chain",
    "state",
    "rpc",
    "grandpa",
    "offchain",
    "childstate",
    "syncstate",
    "payment",
]
ws-port = 8546

[pprof]
enabled = false
listening-address = "localhost:6060"
block-rate = 0
mutex-rate = 0
