version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = [
    "docs/**/*",
    "tests/**/*",
    "scripts/**/*",
    "cmd/gossamer/test_inputs/*",
    "chain/**/*",
    "dot/config/**/*",
    "dot/rpc/modules/test_data",
    "lib/runtime/test_data",
    "**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_paths = ["github.com/ChainSafe/gossamer"]
