on:
  pull_request:
    # Commented paths to avoid skipping required workflow
    # See https://github.community/t/feature-request-conditional-required-checks/16761
    # paths:
    #   - .github/workflows/docker-stable.yml
    #   - "**/*.go"
    #   - "chain/**"
    #   - "cmd/**"
    #   - "dot/**"
    #   - "internal/**"
    #   - "lib/**"
    #   - "pkg/**"
    #   - scripts/integration-test-all.sh
    #   - go.mod
    #   - go.sum
name: docker-stable

jobs:
  docker-stable-tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: docker/build-push-action@v2
        with:
          load: true
          target: builder
          tags: chainsafe/gossamer:test

      - name: Run stable tests
        run: |
          docker run chainsafe/gossamer:test sh -c "make it-stable"
